version: '3.8'

services:
  # Base de datos MongoDB
  mongodb:
    image: mongo:7.0
    container_name: japasea-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: japasea_db
    volumes:
      - mongodb_data:/data/db
      - ./server/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - japasea-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Servidor Node.js
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: japasea-server
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGODB_URI: mongodb://admin:adminpassword@mongodb:27017/japasea_db?authSource=admin
      JWT_SECRET: japasea_jwt_secret_key_2024_dev
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 7d
      BCRYPT_SALT_ROUNDS: 12
      CORS_ORIGIN: http://localhost:5173
      RATE_LIMIT_WINDOW: 900000
      RATE_LIMIT_MAX: 100
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - japasea-network
    command: ["dumb-init", "npm", "run", "dev"]

  # Cliente React/Vite
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: japasea-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3001
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - japasea-network
    command: ["dumb-init", "npm", "run", "dev", "--", "--host", "0.0.0.0"]

  # Mongo Express (Interfaz web para MongoDB)
  mongo-express:
    image: mongo-express:1.0.2
    container_name: japasea-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpassword
      ME_CONFIG_MONGODB_URL: mongodb://admin:adminpassword@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - japasea-network

volumes:
  mongodb_data:
    driver: local

networks:
  japasea-network:
    driver: bridge
